[project]
name = "arborist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brady Johnston", email = "brady.johnston@me.com" }
]
requires-python = ">=3.13"
dependencies = [
    "nodebpy>=520.26.0",
]

[project.scripts]
arborist = "arborist:main"

[project.optional-dependencies]
dev = [
    # "bpy>=5.2.*",
    "fake-bpy-module>=20260419",
    "extbpy>=0.1.0",
    "pytest>=9.0.2",
    "quarto-cli>=1.9",
    "quartodoc>=0.11",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "arborist",
]

[tool.uv.sources]
extbpy = { path = "../extbpy" }
